build:
  version: "3.0"

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "Ankit Patel - Developer"
    email: "ankitpatel3190@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
