build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Ankit Patel - Developer"
    email: "ankitpatel3190@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932